### ISSUE TITLE
Generate viable Hyperledger chaincode

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#107]
The generated chaincode might not support any transactions yet, but it can be deployed on Fabric and initialized.

**Comment by broomweed** [comment]
This one really depends on how long it takes me to get the Fabric issues sorted. I guess I'd give that ~4 days? Once that's done, getting the thing to actually run shouldn't be too hard -- I just have to swap out ChaincodeBaseMock for the real ChaincodeBase and maybe add a mock 'initialize' method so the chaincode can actually start up. So I'll budget 5 days for this one, since I don't know what other kinds of strange issues might crop up.

**Comment by broomweed** [comment]
These are the directions that worked for me to get chaincode running in dev mode: https://hyperledger-fabric.readthedocs.io/en/v1.0.5/peer-chaincode-devmode.html

However, note that at present, in order to get Java support, you have to compile in experimental mode, by editing `$GOPATH/src/github.com/hyperledger/fabric/Makefile` and ensuring that `EXPERIMENTAL` is set to `true`. Then move the new binaries (`peer`, etc) to somewhere on your path.

In addition, since the above instructions are for Go, there are some changes that you need to make to the instructions; notably, you need to compile the chaincode to a file called `chaincode.jar`, and when passing the `-p` argument to `peer chaincode install`, use the _directory_ where `chaincode.jar` is found. (The path given is relative to a certain directory, as well, I think.)

And, `peer chaincode install` and `peer chaincode instantiate` need the additional flag `-l java` so that they know it's in Java.

Also, the directions there say to use `CORE_PEER_ADDRESS=127.0.0.1:7052`, but this doesn't work for me -- for one thing, I have to use a different IP address, which is printed out by `peer` and changes every time. In addition, I have to pass this to the `SimpleSample` chaincode using the `-a` flag, because otherwise it constructs an improper address (by trying to add `:7051` to `127.0.0.1:7052`, which isn't even the right port number for v1.1.) I think this is probably something we can fix in the generated Obsidian code, though.

**Comment by mcoblenz** [comment]
https://github.com/mcoblenz/Obsidian/pull/122
