### ISSUE TITLE
Implement insurance case study bid workflow

### ISSUE THREAD

**Issue by mcoblenz** [mcoblenz/Obsidian#108]
Implement the "successful bid" case that we diagrammed on my whiteboard. There should be appropriate checks for error conditions, etc. but for now they can assert false or otherwise terminate.

**Comment by pkoronkevich** [comment]
Some estimates:
1. Supporting imports in contracts other than the client contract. My guess is this would take a day, only because the client currently can handle importing files. I assume most of the work will be done in the typechecker, so most of the day would be spent looking through the code to see how one would support imports. Code generation would hopefully be straightforward since Java already supports importing other files. However, this is probably not our highest priority.

2. Support a (basic) interaction between an Insurance client and the Insurer (i.e. request an integer from the Insurer). These transactions have to be done through the Insurance service. I believe this would take a day.

3. Support a more robust interaction between an Insurance client and the Insurer (i.e. request a Bid from the Insurer). Again, have to be done through the Insurance service. I believe this would also take a day.

4. Support interactions between Insurer and Bank. Since the design of this is still fuzzy in my mind, I would assume this would take at least a day, if not two. 

5. After supporting robust interactions between the Insurer and Insurance client, and Insurer and Bank, I think I would need two days to put it together using the Insurance service, to finish the diagram.

**Comment by mcoblenz** [comment]
https://github.com/mcoblenz/Obsidian/pull/120

**Comment by pkoronkevich** [comment]
PR #120 commit 68b5380381e0c1efac9221cc68655ef8524c4574
