### ISSUE TITLE
Unexpected ReentrancyException when calling another method on the same object

### ISSUE THREAD

**Issue by ishantheperson** [mcoblenz/Obsidian#282]
The following contract will raise `ReentrancyException` when invoking transaction `foo`:

```
main contract FabCar {
  transaction foo() returns int {
    return bar();
  }

  transaction bar() returns int {
    return 5;
  }
}
```

It seems that in the generated Java code for `foo`, `__isInsideInvocation` is set to `true` before calling `bar`. Then `bar` sees that `__isInsideInvocation` is true, and raises `ReentrancyException`. 

Sorry if I'm missing something - from the documentation it didn't seem like there was any such restriction on transactions.

**Comment by ReedOei** [comment]
Hi, not sure if this is in the documentation or not, but this is disallowed because public transactions may temporarily put the object into an illegal state, which may not match with the assumptions of the 
called transaction. In this case, it's fine, but it can be difficult to detect this without the proper annotations, which can be provided in private helpers. See the following for more information:

"Re-entrancy imposes a significant problem here: re-entrant calls from the middle of a transaction’s body, where the fields may not be consistent with their types, can be dangerous, since
the called transactions are supposed to be allowed to assume that the fields reference objects
consistent with the fields’ types. To address this, Obsidian distinguishes between public and private transactions. Obsidian forbids re-entrant calls to public transactions at the object level of
granularity (i.e., a transaction cannot invoke another transaction on an object for which there is
already an invocation on the stack). The Obsidian runtime detects illegal re-entrant calls and aborts
transactions that attempt them. However, to facilitate helper transactions, Obsidian also supports
private transactions, which declare the expected types of the fields before and after the invocation. " (page 12 of [this paper](https://arxiv.org/pdf/1909.03523.pdf)).

**Comment by ishantheperson** [comment]
Got it, thanks!

**Comment by mcoblenz** [comment]
Thanks for the explanation, Reed! I'd love to relax this check at some point, since this is indeed a bit restrictive and surprising.
